NAME=real
TARGET=ee
KIND=lib

SELF := $(shell pwd)

INCS = -I$(SELF)/include

VPATH := ps2

# sources
SRCS = timer.cpp \
       mem.cpp \
       thread.cpp \
       filesys.cpp \
	filedev.cpp

include $(TOP)/build/core.mk