# CMake platform settings for PlayStation 2

set(CMAKE_EXECUTABLE_SUFFIX ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_C "${CMAKE_EXECUTABLE_SUFFIX}")
set(CMAKE_EXECUTABLE_SUFFIX_CXX "${CMAKE_EXECUTABLE_SUFFIX}")

# Don't want prefixes for ERL's
#set(CMAKE_SHARED_LIBRARY_PREFIX "")
#set(CMAKE_SHARED_LIBRARY_PREFIX_C "")
#set(CMAKE_SHARED_LIBRARY_PREFIX_CXX "")

#set(CMAKE_SHARED_LIBRARY_SUFFIX ".erl")
#set(CMAKE_SHARED_LIBRARY_SUFFIX_C "${CMAKE_SHARED_LIBRARY_SUFFIX}")
#set(CMAKE_SHARED_LIBRARY_SUFFIX_CXX "${CMAKE_SHARED_LIBRARY_SUFFIX}")

